import type { Metadata } from "next";
import { Providers } from './Providers';
import { FontRoboto } from './fonts/fonts';
import "./styles/index.css";
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='dark'>
      <body className={`${FontRoboto.variable} antialiased`}>
        <Providers>
          {children}
          <Toaster position='bottom-center'/>
        </Providers>
      </body>
    </html>
  );
}
